module "network" {
  source = "./modules/network"

  vpc_cidr        = var.vpc_cidr
  vm_private_cidr = var.vm_private_cidr
}

module "host" {
  source = "./modules/host"

  host                 = var.vm_ip
  ssh_user             = var.ssh_user
  ssh_private_key_path = pathexpand(var.ssh_private_key_path)
}

module "firewall" {
  source = "./modules/firewall"

  host                 = module.host.ip
  ssh_user             = var.ssh_user
  ssh_private_key_path = pathexpand(var.ssh_private_key_path)
  ssh_cidrs            = var.admin_cidrs
  public_tcp_ports     = var.public_tcp_ports
}

module "iam" {
  source = "./modules/iam"

  host                 = module.host.ip
  ssh_user             = var.ssh_user
  ssh_private_key_path = pathexpand(var.ssh_private_key_path)
  operator_user        = var.operator_user
  operator_public_key  = trimspace(file(pathexpand(var.ssh_public_key_path)))
}

# Hand-off to Ansible: inventory and network parameters.
resource "local_file" "inventory" {
  filename        = "${path.module}/../ansible/inventory.ini"
  file_permission = "0644"
  content = templatefile("${path.module}/templates/inventory.ini.tftpl", {
    host        = module.host.ip
    user        = var.ssh_user
    key_path    = var.ssh_private_key_path
    pubkey_path = var.ssh_public_key_path
  })
}

resource "local_file" "network_vars" {
  filename        = "${path.module}/../ansible/group_vars/all/network.yml"
  file_permission = "0644"
  content = "# Generated by Terraform (module.network). Do not edit.\n${yamlencode({
    app_subnet  = module.network.app_subnet
    app_gateway = module.network.app_gateway
  })}"
}
